FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

# W czasie uruchomienia: migracje + start
CMD sh -c "npx prisma migrate deploy && node dist/main"
